name: RubyCritic

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6

      - name: Install rubycritic
        run: gem install rubycritic

      - name: RubyCritic App
        run: mkdir -p ${{ runner.temp }}/rubycritic && rubycritic --no-browser -p ${{ runner.temp }}/rubycritic/rubycritic-app -s 90 src app config lib

      - name: RubyCritic on Tests
        run: mkdir -p ${{ runner.temp }}/rubycritic && rubycritic --no-browser -p ${{ runner.temp }}/rubycritic/rubycritic-app -s 65 spec test